---
# tasks file for nginx-magent2
- name: make sure required packages are installed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - nginx

- name: add nginx config
  template:
    src: ./nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
  - restart nginx
